DAC6-2196 : solename nunjk transform
hmrc/register-for-exchange-of-information-frontend pull request #244
Opened 2022-12-28 12:46 UTC by AashuChauhanHmrc

2022-12-28 13:02 UTC, HarryHamilton approved these changes

2022-12-28 13:54 UTC, HarryHamilton approved these changes

2022-12-29 14:03 UTC, HarryHamilton requested changes

2022-12-29 14:03 UTC, HarryHamilton commented on test/controllers/SoleNameControllerSpec.scala
> -  "WhatIsYourName Controller" - {
Should this have been deleted?

2022-12-29 14:11 UTC, AashuChauhanHmrc commented on test/controllers/SoleNameControllerSpec.scala
> -  "WhatIsYourName Controller" - {
fixed it. Thank you.

2022-12-29 15:43 UTC, HarryHamilton approved these changes

2022-12-29 16:19 UTC, merged