DAC6-2675 : Content changes
hmrc/register-for-exchange-of-information-frontend pull request #286
Opened 2023-08-21 09:27 UTC by AashuChauhanHmrc

2023-08-21 09:34 UTC, matthewharris1 approved these changes

2023-08-21 09:35 UTC, matthewharris1 requested changes
I don't think you need the .asPageHeading() anymore as you've added a new heading above the radio buttons.

2023-08-21 10:12 UTC, matthewharris1 submitted a review, later dismissed

2023-08-22 13:28 UTC, BriWak approved these changes

2023-08-22 18:01 UTC, merged